image: node

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main
